name: character
version: '1.0-SNAPSHOT'
main: me.invis.character.Characters
api-version: '1.19'
softdepend:
  - PlaceholderAPI
commands:
  whomadethis:
  character:
    aliases: [characterof]
  createcharacter:
    aliases: [createchar, newchar, newcharacter]
  wardrobe:
    aliases: [characters]
  setcharacterage:
    aliases: [setage, changeage, charage, characterage]
  setcharacterdescription:
    aliases: [setmydescription, changedescription]